baseURL = 'https://hey.iamyourjun.com'
languageCode = 'en-us'
title = 'Junbeom In'
theme = "terminal"

[module]
  # this is needed when you fetch the theme as a submodule to your repo.
  # replacements = "github.com/panr/hugo-theme-terminal/4 -> themes/terminal"
[[module.imports]]
  path = 'github.com/panr/hugo-theme-terminal/v4'